# Generated by Django 3.0.7 on 2020-06-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200613_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='number',
        ),
    ]
