# Generated by Django 3.0.7 on 2020-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200613_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number'),
        ),
    ]
