# Generated by Django 3.0.7 on 2020-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200617_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterToVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('check_url', models.URLField(blank=True, max_length=255, null=True)),
                ('register_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
    ]
