# Generated by Django 3.0.7 on 2020-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_registertovote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
