# Generated by Django 3.0.7 on 2020-07-06 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_candidate_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
