# Generated by Django 3.0.7 on 2020-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_candidate_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='quote',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
