# Generated by Django 3.0.7 on 2020-07-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_candidate_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=60, null=True)),
                ('l_name', models.CharField(blank=True, max_length=60, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='polls/')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate')),
            ],
            options={
                'ordering': ['candidate', 'f_name'],
            },
        ),
    ]
