# Generated by Django 3.0.7 on 2020-07-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_endorsement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='polls.Candidate'),
        ),
    ]
