# Generated by Django 3.0.7 on 2020-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200706_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
