# Generated by Django 3.0.8 on 2020-07-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_candidate_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
