# Generated by Django 3.0.8 on 2020-07-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200726_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
