# Generated by Django 3.0.8 on 2020-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='description_heading',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
