# Generated by Django 3.0.8 on 2020-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_response_description_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
