# Generated by Django 3.0.8 on 2020-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200729_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='quote',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
